# PostgreSQL Client Authentication Configuration File
# TYPE  DATABASE        USER            ADDRESS                 METHOD

# Локальные подключения
local   all             all                                     trust
host    all             all             127.0.0.1/32            md5
host    all             all             ::1/128                 md5

# Обычные подключения для приложения
host    all             all             all                     md5

# Репликационные подключения
host    replication     replicator      172.18.0.0/16           md5
host    replication     replicator      all                     md5

# Разрешаем подключения для пользователя БД из любой сети
host    otus_hw         otus_hw         0.0.0.0/0               md5 