version: '3.8'

services:
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: otus_hw
      POSTGRES_PASSWORD: otus_hw
      POSTGRES_DB: otus_hw
    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    command: python -m src.app
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data: