scope: otus_cluster
name: pg-node

restapi:
  listen: 0.0.0.0:8008
  connect_address: 0.0.0.0:8008

etcd3:
  hosts: etcd:2379

postgresql:
  listen: 0.0.0.0:5432
  connect_address: 0.0.0.0:5432
  data_dir: /var/lib/postgresql/data
  parameters:
    hot_standby: on
  authentication:
    superuser:
      username: postgres
      password: otus_hw
    replication:
      username: replicator
      password: repl_password
  pg_hba:
    - host all all 0.0.0.0/0 md5
    - host replication replicator 0.0.0.0/0 md5

bootstrap:
  dcs:
    synchronous_mode: true
    synchronous_mode_strict: true
    synchronous_node_count: 1
  initdb:
    - encoding: UTF8
    - data-checksums
  users:
    postgres:
      options:
        - createrole
        - createdb

